# Generated by Django 4.0.4 on 2022-05-11 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_remove_blogsite_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsite',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogsite',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='myapp'),
        ),
    ]
