# Generated by Django 4.0.4 on 2022-05-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_blogsite_author_alter_blogsite_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsite',
            name='img',
            field=models.ImageField(null=True, upload_to='myapp'),
        ),
    ]
